version: "3.2"
services:
  api:
    image: nba_flask_api
    container_name: nba_api
    build:
      context: ./api
      target: build
    ports:
      - "80:5000"
    environment:
      - FLASK_APP=app
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    depends_on:
      - redis
      - model

  redis:
    image: redis:6.2.6

  model:
    image: nba_ml_service
    container_name: nba_model
    build:
      context: ./model
      target: build
    depends_on:
      - redis